version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - rust

  - package-ecosystem: cargo
    directory: /lenzu
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - rust

  - package-ecosystem: npm
    directory: /lenzu_server
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - npm
